<?php echo $this->render("includes/header.phtml")?>
<div id="header">
	<div class="w">
		<div id="logo"><a href="/">LoudBite.com</a></div>
		<div id="mainmenu">
			<ul>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/account/accountmanager"><span>My Account</span></a></li>
				<li class="selected"><a href="/artist/list"><span>View All Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/artist/new"><span>Add Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');">
					<a href="/account/logout"><span>Log Out</span></a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div id="content" class="w">
<ul class="nav nav-pills">
    <li>
    	<a href="/artist/video-list?artist=<?php echo $this->artist?>">
    	Videos</a>
    </li>
    <li class="active">
    	<a href="#">
    	Photos</a>
    </li>
    <li>
    	<a href="/artist/list-Cds?artist=<?php echo $this->artist?>">CDs</a>
    </li>
</ul>



<?php
if($this->photos->totalResults() > 0){
?>
<ul class="thumbnails">
<?php 
  foreach($this->photos as $photo){
    $thumbnail = $photo->Small->uri;
    //$original = $photo->Original->uri;
?>
<li class="span3">
    <a href='<?php echo $thumbnail ?>' target='_blank'>
    <img src='<?php echo $thumbnail ?>' class="img-rounded">
    </a>
</li>    
<?php
  }
?> 
</ul>
<?php 
}else{ ?>
We're sorry there were no photos available.
<?php } ?>
<?php echo $this->render("includes/footer.phtml"); ?>
</div>    