<?php echo $this->render('includes/header.phtml')?>
<div id="header">
	<div class="w">
		<div id="logo"><a href="/">LoudBite.com</a></div>
		<div id="mainmenu">
			<ul>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/account/accountmanager"><span>My Account</span></a></li>
				<li class="selected"><a href="/artist/list"><span>View All Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/artist/new"><span>Add Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');">
					<a href="/account/logout"><span>Log Out</span></a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div id="content" class="w">
<table border='0' width='600'>
<?php 
if($this->paginator){

	echo " <tr><td><b>Total Artists:</b> ".
		$this->paginator->getTotalItemCount()."</td></tr>";
	
	foreach($this->paginator as $item){
		echo "<tr><td><a href='/artist/video-list?artist=".$item['artist_name']."'>".
						$item['artist_name']."</a></td></tr>";
	}
	
	echo "<tr><td>";
	echo $this->paginationControl($this->paginator,
			'Sliding',
			'includes/paginationcontrol.phtml');
	echo "</td></tr>";
	
}else{?>

	<tr><td>There were no artists present in the system.
    Add one now!</td></tr>
<?php 
}
?>	

</table>
</div>

<?php echo $this->render("includes/footer.phtml"); ?>
