<?php echo $this->render('includes/header.phtml')?>

<table border='0' width='600'>

<?php 
if($this->paginator){

	echo " <tr><td><b>Total Artists:</b> ".
		$this->paginator->getTotalItemCount()."</td></tr>";
	
	foreach($this->paginator as $item){
		echo "<tr><td>".$item['artist_name']."</td></tr>";
	}
	
	echo "<tr><td>";
	echo $this->paginationControl($this->paginator,
			'Sliding',
			'includes/paginationcontrol.phtml');
	echo "</td></tr>";
	
}else{?>

	<tr><td>There were no artists present in the system.
    Add one now!</td></tr>
<?php 
}
?>	

</table>
<?php echo $this->render("includes/footer.phtml"); ?>
