<?php echo $this->render("includes/header.phtml")?>
<div id="content" class="w">
<?php
if($this->photos->totalResults() > 0){
  foreach($this->photos as $photo){
    $thumbnail = $photo->Thumbnail->uri;
    $original = $photo->Original->uri;
?>
    <?php
    if(!empty($original)){?>
    <a href='<?php echo $original ?>'>
    <?php }?>
    <img src='<?php echo $thumbnail ?>' class="img-rounded">
    <?php {?>
    </a>
    <?php }?>
<?php
  }
}else{ ?>
We're sorry there were no photos available.
<?php } ?>
<?php echo $this->render("includes/footer.phtml"); ?>
</div>    