<?php echo $this->render("includes/header.phtml")?>
<div id="header">
	<div class="w">
		<div id="logo"><a href="/">LoudBite.com</a></div>
		<div id="mainmenu">
			<ul>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/account/accountmanager"><span>My Account</span></a></li>
				<li class="selected"><a href="/artist/list"><span>View All Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/artist/new"><span>Add Artists</span></a></li>
				<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');">
					<a href="/account/logout"><span>Log Out</span></a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div id="content" class="w">
<ul class="nav nav-pills">
 	<li>
    	<a href="/artist/video-list?artist=<?php echo $this->artist?>">
    	Videos</a>
    </li>
    <li>
    	<a href="/artist/list-photos?artist=<?php echo $this->artist?>">
    	Photos</a>
    </li>
    <li class="active">
    	<a href="#">CDs</a>
    </li>
</ul>	    
<?php if($this->products->totalResults()) {?>
<table class="table table-hover" width="300">

	<tr><td colspan="2">You might be interested in these items</td></tr>

	<?php foreach($this->products as $product) {?>
		<tr><td><img src="<?php echo $product->SmallImage->Url ?>" width="50"
       height="50"></td>
		<td>
	     <a href="<?php echo $product->DetailPageURL ?>"><?php echo $product->Title ?>
   		 </a>
  		</td></tr>
	<?php } ?>
		
</table>
<?php } ?>
</div>

<?php echo $this->render('includes/footer.phtml') ?>
		