<?php echo $this->render("includes/header.phtml")?>
<?php 
foreach($this->videos as $video)
{
	$title = $video->getVideoTitle();
	$uri = $video->getVideoWatchPageUrl();
	$description = $video->getVideoDescription();
	$thumbnails = $video->getVideoThumbnails();
	$duration = $video->getVideoDuration();
	$thumbnail = $thumbnails[1]['url'];
	$ratingInfo = $video->getRating();
?>
<table>
<tr><td><img src='<?php echo $thumbnail ?>' height=50 width=50></td>
   <td valign="top"><a href='<?php echo $uri ?>'><?php echo $title ?></a><br>
   Duration <?php echo $duration ?> sec<br>
	Avg Rating: <?php echo $ratingInfo->average ?><br>
	Total Rated: <?php echo $ratingInfo->numRaters ?></td>
</tr>
</table>

<?php
}
?>
<?php echo $this->render('includes/footer.phtml') ?>
