<?php echo $this->render("includes/header.phtml"); ?>

<div id="content" class="w">
<h2>LoudBite My Page - <?php echo $this->escape($this->username); ?></h2>
<!--- MAIN CONTAINER -->
<table class="table">
<tr><td valign="top">
<!--PROFILE DATA-->
<table class="table ">
<tr><td>Username: <?php echo $this->escape($this->username); ?></td></tr>
<tr><td>Date Joined: <?php echo $this->dateJoined?></td></tr>
</table>
</td>
<td valign="top">
<!--FAVORITE BAND LIST-->
<table class="table table-hover">
<?php if($this->artists){?>
<tr align="center">
<td><b>Artist Name</b></td>
<td><b>Date Became A Fan</b></td>
</tr>
<?php foreach($this->artists as $artist){?>
<tr>
<td><a href='/artist/video-list?artist=<?php echo
urlencode($artist['artist_name'])?>'>
<?php echo $this->escape($artist['artist_name']); ?></a></td>
<td><?php echo $this->escape($artist['date_became_fan']); ?></td></tr>
<?php }
}else{
?>
<tr><td>You currently have no favorite artists.</td></tr>
<?php }?>
</table>
</td>
</tr>

</table>
</div>
<?php echo $this->render("includes/footer.phtml"); ?>

