<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <?php echo $this->headTitle('LoudBite.com - Login'); ?>
</head>

<link href="/style.css" rel="stylesheet" type="text/css">
<script language="javascript" src="/jquery.js"></script>
<body>
	<div id="container">
		<div id="header">
			<div class="w">
				<div id="logo"><a href="/">LoudBite.com</a></div>
				<div id="mainmenu">
					<ul>
						<li class="selected"><a href="/account/new"><span>Sign Up</span></a></li>
						<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/artist/list-all-artists"><span>View All Artists</span></a></li>
						<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/artist/new"><span>Add Artists</span></a></li>
						<li onMouseMove="$('.submenu',this).show();$(this).addClass('hover');"  onMouseOut="$('.submenu',this).hide();$(this).removeClass('hover');"><a href="/product/quick-product-display"><span>My Store</span></a></li>
					</ul>
				</div>
			</div>
		</div>
		<div id="content" class="w">

