<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <?php echo $this->headTitle('LoudBite.com - Share your favourite Singers'); ?>
</head>
<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="/css/style.css" rel="stylesheet" type="text/css">
<script language="javascript" src="/jquery.js"></script>
<body>
	<div id="container">
		

